apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: development
  labels:
    app: graphql
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      namespace: development
      labels:
        app: graphql
    spec:
      containers:
      - name: graphql
        image: registry.gitlab.com/pshenmic/ivend/graphql:$CIRCLE_SHA1
        imagePullPolicy: Always
        ports:
          - containerPort: 4000
        readinessProbe:
          httpGet:
            path: /graphql
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - configMapRef:
              name: graphql-config
      imagePullSecrets:
      - name: gitlabregistrycred
