version: '3.7'

services:
  graphql_api:
    build:
      context: ./
    environment:
      - "NODE_ENV=production"
      - "POSTGRES_HOST=postgres"
      - "POSTGRES_USER=ivend"
      - "POSTGRES_PASSWORD=ivend"
      - "POSTGRES_DB=ivend"
      - "REDIS_HOST=cache"
      - "NO_AUTH=1"
    ports:
      - "4000:4000"
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 15s
  postgres:
    image: postgres
    environment:
      - "POSTGRES_USER=ivend"
      - "POSTGRES_PASSWORD=ivend"
      - "POSTGRES_DB=ivend"
    # TODO add volume
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 15s
  cache:
    image: redis
    restart: always
