apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: production
  labels:
    app: graphql
spec:
  replicas: 7
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      namespace: production
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: cr.yandex/crpfb8t478v3of681kce/graphql:1.6.15
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: graphql-config
      imagePullSecrets:
        - name: gitlabregistrycred
