version: 2

jobs:
  build:
    docker:
      - image: circleci/node:11.1.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          - v1-dependencies-{{ checksum "package.json" }}-
          - v1-dependencies-

      - run: npm install
      - run: npm run lint

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

  build_and_push_docker:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-docker-ivend-graphql-{{ .Branch }}-
          - v1-docker-ivend-graphql-
      - deploy:
          name: Push application Docker image
          command: |
            docker load -i .circleci/docker_cache/docker_layer_cache.tar || true

            docker build -t "registry.gitlab.com/pshenmic/ivend/graphql" --cache-from registry.gitlab.com/pshenmic/ivend/graphql .

            docker login registry.gitlab.com -u "pshenmic" -p "$GITLAB_TOKEN"
            docker push "registry.gitlab.com/pshenmic/ivend/graphql"

            docker save -o .circleci/docker_cache/docker_layer_cache.tar \
            registry.gitlab.com/pshenmic/ivend/graphql
      - save_cache:
          paths:
            - .circleci/docker_cache
          key: v1-docker-ivend-graphql-{{ .Branch }}-{{ epoch }}

  deploy:
    docker:
      - image: circleci/node:11.1.0

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "49:d0:99:ae:33:c3:33:11:f9:5c:9e:85:44:90:2b:78"
      - run:
          name: Keyscan deploy server
          command: ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts

      - run:
          name: Deploy
          command: ssh root@$DEPLOY_SERVER 'source /opt/.env && cd /opt/graphql-api && git pull && microk8s.kubectl apply -f kube-config.yml'

workflows:
  version: 2
  graphql_api_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
      - build_and_push_docker:
          filters:
            branches:
              only:
                - master
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build_and_push_docker
