const MachineLogType = {
    "CONNECTION": "ENABLED",
    "COINACCEPTOR": "COINACCEPTOR",
    "BILLACCEPTOR": "BILLACCEPTOR",
    "BUS_ERROR": "BUS_ERROR",
    "REGISTRATION": "REGISTRATION",
    "KKT": "KKT",
    "ALL": "ALL",
    "TERMINAL": "TERMINAL",
    "NO_COINS_24H": "NO_COINS_24H",
    "NO_CASH_24H": "NO_CASH_24H",
    "NO_CASHLESS_24H": "NO_CASHLESS_24H",
    "NO_RECEIPT_24H": "NO_RECEIPT_24H",
}


module.exports = MachineLogType
