const NotificationType = {
    "CONTROLLER_NO_CONNECTION": "CONTROLLER_NO_CONNECTION",
    "CONTROLLER_NO_SALES": "CONTROLLER_NO_SALES",
    "CONTROLLER_ENCASHMENT": "CONTROLLER_ENCASHMENT",
    "USER_LOW_BALANCE": "USER_LOW_BALANCE",
    "GET_MONTH_SALES": "GET_MONTH_SALES",
    "GET_WEEK_SALES": "GET_WEEK_SALES",
    "GET_DAY_SALES": "GET_DAY_SALES",
    "GET_NEWS": "GET_NEWS",
    "KKT_ERROR": "KKT_ERROR",
    "PINPAD_ERROR": "PINPAD_ERROR",
    "CASH_ACCEPTOR_ERROR": "CASH_ACCEPTOR_ERROR",
}


module.exports = NotificationType
