const NotificationType = {
    "GET_NEWS": "GET_NEWS",
    "ALARM_SMS": "ALARM_SMS",
    "GET_DAY_SALES": "GET_DAY_SALES",
    "GET_WEEK_SALES": "GET_WEEK_SALES",
    "GET_MONTH_SALES": "GET_MONTH_SALES",
    "CONTROLLER_ENCASHMENT": "CONTROLLER_ENCASHMENT",
    "MACHINE_ATTENTION_REQUIRED": "MACHINE_ATTENTION_REQUIRED",
    "CONTROLLER_NO_CONNECTION": "CONTROLLER_NO_CONNECTION",
    "CONTROLLER_NO_SALES": "CONTROLLER_NO_SALES",
    "NO_COINS_24H": "NO_COINS_24H",
    "NO_CASH_24H": "NO_CASH_24H",
    "NO_CASHLESS_24H": "NO_CASHLESS_24H",
    "NO_RECEIPT_24H": "NO_RECEIPT_24H",
    "USER_LOW_BALANCE": "USER_LOW_BALANCE",
}


module.exports = NotificationType
