const NotificationType = {
    "CONTROLLER_NO_CONNECTION": "CONTROLLER_NO_CONNECTION",
    "CONTROLLER_NO_SALES": "CONTROLLER_NO_SALES",
    "CONTROLLER_ENCASHMENT": "CONTROLLER_ENCASHMENT",
    "USER_LOW_BALANCE": "USER_LOW_BALANCE",
    "USER_WILL_BLOCK": "USER_WILL_BLOCK",
}


module.exports = NotificationType
