const Permission = {
    "READ_CONTROLLER": "READ_CONTROLLERS",
    "WRITE_CONTROLLER": "WRITE_CONTROLLER",
    "AUTH_CONTROLLER": "AUTH_CONTROLLER",
    "READ_EQUIPMENT": "READ_EQUIPMENT",
    "WRITE_EQUIPMENT": "WRITE_EQUIPMENT",
    "READ_FISCAL_REGISTRAR": "READ_FISCAL_REGISTRAR",
    "WRITE_FISCAL_REGISTRAR": "WRITE_FISCAL_REGISTRAR",
    "READ_BANK_TERMINAL": "READ_BANK_TERMINAL",
    "WRITE_BANK_TERMINAL": "WRITE_BANK_TERMINAL",
}

module.exports = Permission
