const Permission = {
    "READ_CONTROLLER": "READ_CONTROLLERS",
    "WRITE_CONTROLLER": "WRITE_CONTROLLER",
    "AUTH_CONTROLLER": "AUTH_CONTROLLER",
    "WRITE_EQUIPMENT": "WRITE_EQUIPMENT"
}

module.exports = Permission
